# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8b8ea843cfe7b0c3e516ae9ce71e3dea3d7c268bba59cd45c2d02f669f54bdc110af5c327f490a8568f9f92b081976ada749218e74ba6fb21b78e440ccd0e0fb

test:
  secret_key_base: f53b7d65cb1344f9b4f67137884dd55ef6cbab64797388fc1e330de6234deafe14fd10d4943862a0e6bed1ab1234461767459070e60215739b567d0baae6fb4c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
